parameters:
    banners_dir: '%kernel.project_dir%/public/uploads/banners'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Component\Form\BannerFormObserver:
        autowire: true

    App\System\Upload:
        autowire: true